os: linux
language: generic

addons:
  apt:
    packages:
      - build-essential
      - autoconf
      - automake
      - libtool
      - libgtk2.0-dev
      - libjack-dev
      - libasound2-dev
      - liblash-compat-dev

script:
  - ./autogen.sh
  - ./configure
  - make
